import { Resend } from 'resend';
import { format } from 'date-fns';
import dotenv from 'dotenv';
import type { User, Task, WeekData, TaskStats, TopRisk, ReportEmailData } from '../types/index';

dotenv.config();

const resendApiKey: string = process.env.RESEND_API_KEY || '';

if (!resendApiKey) {
  console.error('[Resend] Missing RESEND_API_KEY in environment variables');
}

export const resend = new Resend(resendApiKey);

const EMAIL_FROM = 'reports@operix.app';

const baseEmailStyles = `
  <style>
    body { margin: 0; padding: 0; background-color: #0A0A0F; color: #F8F8FF; font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; }
    .container { max-width: 600px; margin: 0 auto; padding: 32px 24px; }
    .header { text-align: center; padding: 24px 0; border-bottom: 1px solid #2A2A3A; margin-bottom: 24px; }
    .header h1 { font-size: 20px; font-weight: 700; color: #F8F8FF; margin: 0 0 4px; }
    .header p { font-size: 12px; color: #9898B0; margin: 0; }
    .card { background-color: #16161F; border: 1px solid #2A2A3A; border-radius: 12px; padding: 20px; margin-bottom: 16px; }
    .card-title { font-size: 14px; font-weight: 600; color: #F8F8FF; margin: 0 0 12px; }
    .label { font-size: 12px; color: #9898B0; margin: 0 0 4px; }
    .value { font-size: 18px; font-weight: 700; color: #F8F8FF; margin: 0 0 8px; font-family: 'JetBrains Mono', monospace; }
    .badge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 500; }
    .badge-critical { background-color: rgba(239,68,68,0.15); color: #EF4444; }
    .badge-high { background-color: rgba(245,158,11,0.15); color: #F59E0B; }
    .badge-green { background-color: rgba(34,197,94,0.15); color: #22C55E; }
    .badge-purple { background-color: rgba(168,85,247,0.15); color: #A855F7; }
    .divider { border: none; border-top: 1px solid #2A2A3A; margin: 16px 0; }
    .footer { text-align: center; padding: 24px 0; border-top: 1px solid #2A2A3A; margin-top: 24px; }
    .footer p { font-size: 11px; color: #5A5A72; margin: 0; }
    .risk-bar { height: 6px; border-radius: 3px; background-color: #2A2A3A; overflow: hidden; margin-top: 6px; }
    .risk-fill { height: 100%; border-radius: 3px; }
    .text-muted { color: #9898B0; font-size: 13px; }
    .text-small { color: #5A5A72; font-size: 11px; }
    a { color: #4F6EF7; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
`;

function getRiskColor(score: number): string {
  if (score >= 71) return '#EF4444';
  if (score >= 41) return '#F59E0B';
  return '#22C55E';
}

export async function sendRiskAlertEmail(
  manager: User,
  task: Task,
  riskScore: number
): Promise<void> {
  const riskColor = getRiskColor(riskScore);
  const severityLabel = riskScore >= 90 ? 'CRITICAL' : 'HIGH';
  const severityClass = riskScore >= 90 ? 'badge-critical' : 'badge-high';

  const html = `
    <!DOCTYPE html>
    <html>
    <head>${baseEmailStyles}</head>
    <body>
      <div class="container">
        <div class="header">
          <h1>⚠️ Task Delay Risk Alert</h1>
          <p>Operix Risk Engine</p>
        </div>

        <div class="card">
          <p class="label">Hi ${manager.name},</p>
          <p class="text-muted" style="margin-top: 8px;">
            A task under your management has been flagged with a high delay risk score.
          </p>
        </div>

        <div class="card">
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
            <p class="card-title" style="margin: 0;">${task.title}</p>
            <span class="${severityClass} badge">${severityLabel}</span>
          </div>

          <p class="label">Risk Score</p>
          <p class="value" style="color: ${riskColor};">${riskScore}/100</p>
          <div class="risk-bar">
            <div class="risk-fill" style="width: ${riskScore}%; background-color: ${riskColor};"></div>
          </div>

          <hr class="divider" />

          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 6px 0;"><span class="label">Assigned To</span><br /><span class="text-muted">${task.users?.name || 'Unknown'}</span></td>
              <td style="padding: 6px 0;"><span class="label">Project</span><br /><span class="text-muted">${task.projects?.name || 'Unknown'}</span></td>
            </tr>
            <tr>
              <td style="padding: 6px 0;"><span class="label">Deadline</span><br /><span class="text-muted">${format(new Date(task.deadline), 'dd MMM yyyy')}</span></td>
              <td style="padding: 6px 0;"><span class="label">Current Progress</span><br /><span class="text-muted">${task.progress}%</span></td>
            </tr>
          </table>
        </div>

        <div class="footer">
          <p>This alert was generated by Operix AI Risk Engine</p>
          <p style="margin-top: 4px;">© ${new Date().getFullYear()} KaizenSpark Tech Pvt. Ltd.</p>
        </div>
      </div>
    </body>
    </html>
  `;

  try {
    await resend.emails.send({
      from: EMAIL_FROM,
      to: manager.email,
      subject: `⚠️ Task At Risk: "${task.title}" — Risk Score ${riskScore}/100`,
      html,
    });
    console.log(`[Resend] Risk alert email sent to ${manager.email} for task "${task.title}"`);
  } catch (error) {
    console.error(`[Resend] Failed to send risk alert email:`, error);
  }
}

export async function sendBurnoutAlertEmail(
  manager: User,
  employee: User,
  burnoutScore: number,
  weeks: WeekData[]
): Promise<void> {
  const level = burnoutScore > 75 ? 'CRITICAL' : 'HIGH';
  const levelClass = burnoutScore > 75 ? 'badge-critical' : 'badge-high';
  const weekCompletionRates = weeks
    .map((w, i) => `<tr><td style="padding: 4px 8px;" class="text-muted">Week ${i + 1}</td><td style="padding: 4px 8px;" class="text-muted">${(w.completionRate * 100).toFixed(0)}%</td></tr>`)
    .join('');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>${baseEmailStyles}</head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🔒 Confidential Wellbeing Alert</h1>
          <p>Operix Burnout Detection Engine</p>
        </div>

        <div class="card" style="border-color: #A855F7;">
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
            <p class="card-title" style="margin: 0;">Employee Wellbeing Flag</p>
            <span class="badge badge-purple">CONFIDENTIAL</span>
          </div>
          <p class="text-muted">
            Hi ${manager.name}, our analysis indicates that <strong style="color: #F8F8FF;">${employee.name}</strong>
            may be experiencing elevated workload stress. This is a private notification — only you can see this data.
          </p>
        </div>

        <div class="card">
          <p class="label">Burnout Risk Score</p>
          <p class="value" style="color: ${getRiskColor(burnoutScore)};">${burnoutScore}/100</p>
          <span class="${levelClass} badge">${level} RISK</span>

          <hr class="divider" />

          <p class="card-title">4-Week Completion Rate Trend</p>
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #2A2A3A;">
              <th style="padding: 6px 8px; text-align: left; font-size: 11px; color: #5A5A72;">Week</th>
              <th style="padding: 6px 8px; text-align: left; font-size: 11px; color: #5A5A72;">Completion Rate</th>
            </tr>
            ${weekCompletionRates}
          </table>
        </div>

        <div class="card">
          <p class="card-title">💡 Recommended Action</p>
          <p class="text-muted">
            Schedule a private 1-on-1 check-in with ${employee.name}. Focus on understanding their current
            workload, any blockers, and whether task redistribution would help. Approach with empathy — this
            data is an indicator, not a diagnosis.
          </p>
        </div>

        <div class="footer">
          <p>⚠️ This report is confidential. Do not share with the employee or other team members.</p>
          <p style="margin-top: 4px;">Generated by Operix AI Burnout Detection Engine</p>
          <p style="margin-top: 4px;">© ${new Date().getFullYear()} KaizenSpark Tech Pvt. Ltd.</p>
        </div>
      </div>
    </body>
    </html>
  `;

  try {
    await resend.emails.send({
      from: EMAIL_FROM,
      to: manager.email,
      subject: `🔒 Wellbeing Alert: ${employee.name} — Burnout Risk ${burnoutScore}/100`,
      html,
    });
    console.log(`[Resend] Burnout alert email sent to ${manager.email} for employee "${employee.name}"`);
  } catch (error) {
    console.error(`[Resend] Failed to send burnout alert email:`, error);
  }
}

export function buildReportEmailHTML(data: ReportEmailData): string {
  const topRisksRows = data.topRisks
    .map(
      (risk) => `
      <tr>
        <td style="padding: 6px 8px;" class="text-muted">${risk.title}</td>
        <td style="padding: 6px 8px; color: ${getRiskColor(risk.riskScore)}; font-weight: 600; font-family: 'JetBrains Mono', monospace;">${risk.riskScore}</td>
        <td style="padding: 6px 8px;" class="text-muted">${risk.assignedTo}</td>
        <td style="padding: 6px 8px;" class="text-muted">${risk.deadline}</td>
      </tr>`
    )
    .join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>${baseEmailStyles}</head>
    <body>
      <div class="container">
        <div class="header">
          <h1>📊 Weekly Operations Report</h1>
          <p>${data.period}</p>
        </div>

        <div class="card">
          <p class="label">Hi ${data.managerName},</p>
          <p class="text-muted" style="margin-top: 8px;">
            Here is your weekly operations summary from Operix.
          </p>
        </div>

        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 16px;">
          <div class="card" style="text-align: center;">
            <p class="label">Tasks Completed</p>
            <p class="value" style="color: #22C55E;">${data.taskStats.completed}</p>
          </div>
          <div class="card" style="text-align: center;">
            <p class="label">Completion Rate</p>
            <p class="value" style="color: #4F6EF7;">${data.taskStats.completionRate}%</p>
          </div>
          <div class="card" style="text-align: center;">
            <p class="label">Tasks Delayed</p>
            <p class="value" style="color: #F59E0B;">${data.taskStats.delayed}</p>
          </div>
          <div class="card" style="text-align: center;">
            <p class="label">Newly Overdue</p>
            <p class="value" style="color: #EF4444;">${data.taskStats.newlyOverdue}</p>
          </div>
        </div>

        <div class="card">
          <p class="card-title">AI-Generated Report</p>
          <div class="text-muted" style="white-space: pre-wrap; line-height: 1.6;">
${data.reportContent}
          </div>
        </div>

        ${
          data.topRisks.length > 0
            ? `
        <div class="card">
          <p class="card-title">Top Risk Tasks</p>
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #2A2A3A;">
              <th style="padding: 6px 8px; text-align: left; font-size: 11px; color: #5A5A72;">Task</th>
              <th style="padding: 6px 8px; text-align: left; font-size: 11px; color: #5A5A72;">Risk</th>
              <th style="padding: 6px 8px; text-align: left; font-size: 11px; color: #5A5A72;">Assigned</th>
              <th style="padding: 6px 8px; text-align: left; font-size: 11px; color: #5A5A72;">Deadline</th>
            </tr>
            ${topRisksRows}
          </table>
        </div>`
            : ''
        }

        <div class="footer">
          <p>Generated by Operix AI Report Engine</p>
          <p style="margin-top: 4px;">© ${new Date().getFullYear()} KaizenSpark Tech Pvt. Ltd.</p>
        </div>
      </div>
    </body>
    </html>
  `;
}

export default resend;

