import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { FileText, Plus, Search, Calendar, CheckCircle2, Eye, Download, Mail } from 'lucide-react'
import { format } from 'date-fns'
import ReactMarkdown from 'react-markdown'

import { api } from '@/lib/api'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription } from '@/components/ui/card'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { useToast } from '@/hooks/use-toast'

const fetchReports = async () => {
  const res = await api.get('/reports')
  return res.data.data
}

export function Reports() {
  const { toast } = useToast()
  const queryClient = useQueryClient()
  const [search, setSearch] = useState('')
  const [selectedReport, setSelectedReport] = useState<any | null>(null)

  const { data: reports = [], isLoading } = useQuery({
    queryKey: ['reports'],
    queryFn: fetchReports,
  })

  const generateReport = useMutation({
    mutationFn: async () => {
      const res = await api.post('/reports/generate')
      return res.data
    },
    onSuccess: () => {
      toast({ title: 'Report Generated', description: 'Your weekly report has been generated successfully.' })
      queryClient.invalidateQueries({ queryKey: ['reports'] })
    },
    onError: () => {
      toast({ variant: 'destructive', title: 'Generation Failed', description: 'Failed to generate the AI report.' })
    }
  })

  const formattedReports = reports.map((r: any) => ({
    ...r,
    period: `Week of ${format(new Date(r.week_start), 'MMM dd, yyyy')}`
  }))

  const filteredReports = formattedReports.filter((r: any) => r.period.toLowerCase().includes(search.toLowerCase()))

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">AI Reports</h1>
          <p className="text-muted-foreground mt-1">Weekly executive summaries generated by Operix AI.</p>
        </div>
        <Button onClick={() => generateReport.mutate()} disabled={generateReport.isPending} className="gap-2">
          {generateReport.isPending ? <div className="w-4 h-4 rounded-full border-2 border-primary-foreground border-t-transparent animate-spin" /> : <Plus className="w-4 h-4" />}
          Generate Report
        </Button>
      </div>

      <div className="relative max-w-md">
        <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
        <Input 
          placeholder="Search reports by period..." 
          value={search}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearch(e.target.value)}
          className="pl-9 bg-card border-border"
        />
      </div>

      {isLoading ? (
        <div className="space-y-4">
          {[1, 2, 3].map(i => <div key={i} className="h-24 bg-muted/20 animate-pulse rounded-xl border border-border" />)}
        </div>
      ) : filteredReports.length === 0 ? (
        <div className="text-center py-20 border-2 border-dashed border-border rounded-xl bg-card/50">
          <FileText className="h-12 w-12 mx-auto text-muted-foreground/50 mb-4" />
          <h3 className="text-xl font-semibold">No reports found</h3>
          <p className="text-muted-foreground mt-2">Reports are generated automatically every Monday, or you can generate one manually.</p>
        </div>
      ) : (
        <div className="grid gap-4">
          {filteredReports.map((report: any) => (
            <Card key={report.id} className="border-border hover:shadow-md transition-shadow">
              <CardContent className="p-0">
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between p-6 gap-4">
                  <div className="flex items-start gap-4">
                    <div className="h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center border border-primary/20 shrink-0">
                      <FileText className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-lg">{report.period}</h3>
                      <div className="flex items-center gap-4 text-sm text-muted-foreground mt-1">
                        <span className="flex items-center gap-1"><Calendar className="w-3.5 h-3.5" /> {format(new Date(report.created_at), 'MMM dd, yyyy')}</span>
                        <span className="flex items-center gap-1 text-green-500"><CheckCircle2 className="w-3.5 h-3.5" /> Emailed to Manager</span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-2 w-full sm:w-auto">
                    <Button variant="outline" size="sm" className="w-full sm:w-auto gap-2" onClick={() => setSelectedReport(report)}>
                      <Eye className="w-4 h-4" /> View
                    </Button>
                    <Button variant="ghost" size="icon" className="shrink-0 text-muted-foreground hover:text-foreground">
                      <Download className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <Dialog open={!!selectedReport} onOpenChange={(open) => !open && setSelectedReport(null)}>
        <DialogContent className="sm:max-w-[800px] h-[80vh] flex flex-col border-border bg-card p-0">
          {selectedReport && (
            <>
              <div className="p-6 border-b border-border bg-muted/10 shrink-0">
                <DialogHeader>
                  <DialogTitle className="text-2xl flex items-center gap-2">
                    <FileText className="w-6 h-6 text-primary" />
                    Weekly Report
                  </DialogTitle>
                  <CardDescription className="text-base mt-2">
                    {selectedReport.period}
                  </CardDescription>
                </DialogHeader>
              </div>
              <div className="flex-1 overflow-y-auto p-8 bg-background">
                <div className="prose prose-slate dark:prose-invert max-w-none">
                  <ReactMarkdown>{selectedReport.content}</ReactMarkdown>
                </div>
              </div>
              <div className="p-4 border-t border-border bg-muted/10 shrink-0 flex justify-end gap-2">
                <Button variant="outline" onClick={() => setSelectedReport(null)}>Close</Button>
                <Button className="gap-2"><Mail className="w-4 h-4" /> Forward Report</Button>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}
